name: Publish PowerShell Gallery 
on:
  push:
    branches:
    - 'master'
    

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Ready to Publish Module 
      uses: pcgeek86/publish-powershell-module-action@v20
      id: publish-module
      with:
        NuGetApiKey: ${{ secrets.PS_GALLERY_KEY }}
   
